//
//  SetCards.swift
//  Spellbook Duels
//
//  Created by Ryan Camp on 10/29/25.
//

import UIKit
import SwiftData

extension PresentedCardModel {
    static let fullCardList: [PresentedCardModel] = [ // Numbered to make it easier to keep track
    // 1
        PresentedCardModel(
            name: "Aspect of Cavern",
            text: "Your earth enchantments and items cannot be broken.",
            type: "Charm",
            cost: "2 Aether",
            costVal: 2,
            element: .EARTH,
            image: UIImage(named: "AspectofCavern"),
            icon: nil,
            cardCode: "EAS", // Code is determined by the first letter of its element and then the first two consecutive letters of its name that do not make a duplicate code (as determined by the order going down
            Strength: nil,
            duration: 5,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 2
        PresentedCardModel(
            name: "Steel Shield",
            text: "Passive: While you have no defense spells, aether damage dealt to you is halved (round down).",
            type: "Relic",
            cost: "3 Aether",
            costVal: 3,
            element: .EARTH,
            image: UIImage(named: "SteelShield"),
            icon: nil,
            cardCode: "EST",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 3
        PresentedCardModel(
            name: "Instant Freeze",
            text: "All spells and abilities that have been cast or activated before this potion is activated have no effect. This ability resolves first. Players cannot activate abilities after this potion is activated.",
            type: "Potion",
            cost: "4 Turns to brew",
            costVal: 4,
            element: .WATER,
            image: UIImage(named: "InstantFreeze"),
            icon: nil,
            cardCode: "WIN",
            Strength: nil,
            duration: nil,
            speed: 5,
            hasActivated: false,
            numTargets: nil
        ),
    // 4
        PresentedCardModel(
            name: "Aspect of Tide",
            text: "At the end of your action phase, put a wave counter on this spell and on each of your enchantments that have wave counters on them. When this spell fades or breaks, discard your hand and draw a card for each wave counter on it.",
            type: "Charm",
            cost: "2 Aether",
            costVal: 2,
            element: .WATER,
            image: UIImage(named: "AspectofTide"),
            icon: nil,
            cardCode: "WAS",
            Strength: nil,
            duration: 6,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 5
        PresentedCardModel(
            name: "Aspect of Blaze",
            text: "If you would deal aether damage, you deal twice that damage instead.",
            type: "Charm",
            cost: "2 Aether",
            costVal: 2,
            element: .FIRE,
            image: UIImage(named: "AspectofBlaze"),
            icon: nil,
            cardCode: "FAS",
            Strength: nil,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 6
        PresentedCardModel(
            name: "Sparking Projectile",
            text: "Wards cannot reduce the damage this spell deals.",
            type: "Jinx",
            cost: "2 Aether",
            costVal: 2,
            element: .FIRE,
            image: UIImage(named: "SparkingProjectile"),
            icon: nil,
            cardCode: "FSP",
            Strength: 4,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 7
        PresentedCardModel(
            name: "Gale Force Deflection",
            text: "All damage that would be dealt to you this defense phase is dealt to the attacking opponent instead.",
            type: "Counterspell",
            cost: "3 Aether",
            costVal: 3,
            element: .AIR,
            image: UIImage(named: "GaleForceDeflection"),
            icon: nil,
            cardCode: "AGA",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 8
        PresentedCardModel(
            name: "Aspect of Breeze",
            text: "If you would gain aether, you gain twice that aether instead (this includes for turn).",
            type: "Charm",
            cost: "3 Aether",
            costVal: 3,
            element: .AIR,
            image: UIImage(named: "AspectofBreeze"),
            icon: nil,
            cardCode: "AAS",
            Strength: nil,
            duration: 4,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 9
        PresentedCardModel(
            name: "Wall Reinforcement",
            text: "Wall Reinforcement enters with 6 stone counters on it. Whenever you take aether damage, remove a stone counter from it. Wards you have gain 1 strength for each stone counter on this spell.",
            type: "Charm",
            cost: "3 Aether",
            costVal: 3,
            element: .EARTH,
            image: UIImage(named: "WallReinforcement"),
            icon: nil,
            cardCode: "EWA",
            Strength: nil,
            duration: 6,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 10
        PresentedCardModel(
            name: "Bottled Fortitude",
            text: "The next time you would take damage from an Attack spell, prevent that damage.",
            type: "Potion",
            cost: "2 Turns to Brew",
            costVal: 2,
            element: .EARTH,
            image: UIImage(named: "BottledFortitude"),
            icon: nil,
            cardCode: "EBO",
            Strength: nil,
            duration: nil,
            speed: 3,
            hasActivated: false,
            numTargets: nil
        ),
    // 11
        PresentedCardModel(
            name: "Sleeping Draught",
            text: "The next opponent cannot play spells until the end of their next turn.",
            type: "Potion",
            cost: "3 Turns to brew",
            costVal: 3,
            element: .WATER,
            image: UIImage(named: "SleepingDraught"),
            icon: nil,
            cardCode: "WSL",
            Strength: nil,
            duration: nil,
            speed: 4,
            hasActivated: false,
            numTargets: nil
        ),
    // 12
        PresentedCardModel(
            name: "Building Crescendo",
            text: "Whenever you gain aether, put that many wave counters on Building Crescendo. When this spell fades or breaks, you gain 2 aether for each wave counter on it.",
            type: "Charm",
            cost: "2 Aether",
            costVal: 2,
            element: .WATER,
            image: UIImage(named: "BuildingCrescendo"),
            icon: nil,
            cardCode: "WBU",
            Strength: nil,
            duration: 4,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 13
        PresentedCardModel(
            name: "Stoking the Flames",
            text: "You gain 3 aether each turn instead of 1. If at the end of your turn you have not played a new attack spell, break this charm.",
            type: "Charm",
            cost: "1 Aether",
            costVal: 1,
            element: .FIRE,
            image: UIImage(named: "StokingtheFlames"),
            icon: nil,
            cardCode: "FST",
            Strength: nil,
            duration: 4,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 14
        PresentedCardModel(
            name: "Purifying Fire",
            text: "Break a Curse. Each opponent takes 2 aether damage.",
            type: "Potion",
            cost: "2 Turns to Brew",
            costVal: 2,
            element: .FIRE,
            image: UIImage(named: "PurifyingFire"),
            icon: nil,
            cardCode: "FPU",
            Strength: nil,
            duration: nil,
            speed: 3,
            hasActivated: false,
            numTargets: nil
        ),
    // 15
        PresentedCardModel(
            name: "Flask-Held Gale",
            text: "Break a Ward. Gain aether equal to that card’s cost.",
            type: "Potion",
            cost: "2 Turns to Brew",
            costVal: 2,
            element: .AIR,
            image: UIImage(named: "FlaskHeldGale"),
            icon: nil,
            cardCode: "AFL",
            Strength: nil,
            duration: nil,
            speed: 3,
            hasActivated: false,
            numTargets: nil
        ),
    // 16
        PresentedCardModel(
            name: "Meditation",
            text: "Air spells you cast cost 2 less aether to cast.",
            type: "Charm",
            cost: "2 Aether",
            costVal: 2,
            element: .AIR,
            image: UIImage(named: "Meditation"),
            icon: nil,
            cardCode: "AME",
            Strength: nil,
            duration: 2,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 17
        PresentedCardModel(
            name: "Jar of Dirt",
            text: "The next time you would take aether damage, prevent that damage.",
            type: "Potion",
            cost: "3 Turns to Brew",
            costVal: 3,
            element: .EARTH,
            image: UIImage(named: "JarofDirt"),
            icon: nil,
            cardCode: "EJA",
            Strength: nil,
            duration: nil,
            speed: 5,
            hasActivated: false,
            numTargets: nil
        ),
    // 18
        PresentedCardModel(
            name: "Bonecracker",
            text: "An opponent attacking you takes 3 aether damage. Activate this only during your defend phase.",
            type: "Relic",
            cost: "1 Aether",
            costVal: 1,
            element: .EARTH,
            image: UIImage(named: "Bonecracker"),
            icon: nil,
            cardCode: "EON",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 19
        PresentedCardModel(
            name: "Seer’s Scrying Bowl",
            text: "Passive: You may pay 1 aether to look at the top 3 cards of your spellbook any time you have priority.",
            type: "Relic",
            cost: "1 Aether",
            costVal: 1,
            element: .WATER,
            image: UIImage(named: "SeersScryingBowl"),
            icon: nil,
            cardCode: "WSE",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 20
        PresentedCardModel(
            name: "Scrying Water",
            text: "Look at the top 4 cards of the Spellbook. Choose one of those cards and put it into your hand, then shuffle the rest back into the Spellbook.",
            type: "Potion",
            cost: "1 Turn to Brew",
            costVal: 1,
            element: .WATER,
            image: UIImage(named: "ScryingWater"),
            icon: nil,
            cardCode: "WSC",
            Strength: nil,
            duration: nil,
            speed: 3,
            hasActivated: false,
            numTargets: nil
        ),
    // 21
        PresentedCardModel(
            name: "Greek Fire",
            text: "Each opponent takes 4 aether damage for each enchantment and each item they control.",
            type: "Potion",
            cost: "4 Turns to Brew",
            costVal: 4,
            element: .FIRE,
            image: UIImage(named: "GreekFire"),
            icon: nil,
            cardCode: "FGR",
            Strength: nil,
            duration: nil,
            speed: 4,
            hasActivated: false,
            numTargets: nil
        ),
    // 22
        PresentedCardModel(
            name: "Kindling Staff",
            text: "Deal 3 damage to each opponent without a ward.",
            type: "Relic",
            cost: "1 Aether",
            costVal: 1,
            element: .FIRE,
            image: UIImage(named: "KindlingStaff"),
            icon: nil,
            cardCode: "FKI",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 23
        PresentedCardModel(
            name: "Wax Wings",
            text: "Prevent any damage you would take from non-Fire sources until the end of your next turn.",
            type: "Relic",
            cost: "2 Aether",
            costVal: 2,
            element: .AIR,
            image: UIImage(named: "WaxWings"),
            icon: nil,
            cardCode: "AWA",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 24
        PresentedCardModel(
            name: "Breath of Fresh Air",
            text: "You gain 4 aether.",
            type: "Potion",
            cost: "3 Turns to Brew",
            costVal: 3,
            element: .AIR,
            image: UIImage(named: "BreathofFreshAir"),
            icon: nil,
            cardCode: "ABR",
            Strength: nil,
            duration: nil,
            speed: 4,
            hasActivated: false,
            numTargets: nil
        ),
    // 25
        PresentedCardModel(
            name: "Earth Wand",
            text: "Passive: Earth wards and counterspells you cast have 3 extra strength.",
            type: "Relic",
            cost: "2 Aether",
            costVal: 2,
            element: .EARTH,
            image: UIImage(named: "EarthWand"),
            icon: nil,
            cardCode: "EEA",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 26
        PresentedCardModel(
            name: "Insurmountable",
            text: "Prevent all damage that would be dealt to you this turn.",
            type: "Counterspell",
            cost: "5 Aether",
            costVal: 5,
            element: .EARTH,
            image: UIImage(named: "Insurmountable"),
            icon: nil,
            cardCode: "EIN",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 27
        PresentedCardModel(
            name: "Refraction Mirage",
            text: "Flip a coin. If it lands on heads, prevent all damage that would be dealt to you this turn. If tails, prevent half that damage instead, rounded down.",
            type: "Counterspell",
            cost: "3 Aether",
            costVal: 3,
            element: .WATER,
            image: UIImage(named: "RefractionMirage"),
            icon: nil,
            cardCode: "WRE",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 28
        PresentedCardModel(
            name: "Water Wand",
            text: "Passive: Whenever you cast a Water enchantment, you gain 3 aether.",
            type: "Relic",
            cost: "2 Aether",
            costVal: 2,
            element: .WATER,
            image: UIImage(named: "WaterWand"),
            icon: nil,
            cardCode: "WWA",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 29
        PresentedCardModel(
            name: "Fire Wand",
            text: "Passive: Whenever you cast a Fire spell, each opponent loses 1 aether.",
            type: "Relic",
            cost: "1 Aether",
            costVal: 1,
            element: .FIRE,
            image: UIImage(named: "FireWand"),
            icon: nil,
            cardCode: "FFI",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 30
        PresentedCardModel(
            name: "Blazing Counter",
            text: "The attacking opponent takes 3 aether damage.",
            type: "Counterspell",
            cost: "3 Aether",
            costVal: 3,
            element: .FIRE,
            image: UIImage(named: "BlazingCounter"),
            icon: nil,
            cardCode: "FBL",
            Strength: 4,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 31
        PresentedCardModel(
            name: "Countergale",
            text: "Prevent half the damage you would take this defense phase (round up).",
            type: "Counterspell",
            cost: "1 Aether",
            costVal: 1,
            element: .AIR,
            image: UIImage(named: "Countergale"),
            icon: nil,
            cardCode: "ACO",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 32
        PresentedCardModel(
            name: "Air Wand",
            text: "Passive: Whenever you cast an Air spell, you gain 3 aether.",
            type: "Relic",
            cost: "2 Aether",
            costVal: 2,
            element: .AIR,
            image: UIImage(named: "AirWand"),
            icon: nil,
            cardCode: "AAI",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 33
        PresentedCardModel(
            name: "Hurried Wall",
            text: "Practicers of the lithomantic arts may not always have time to put up indomitable fortifications. In this case, a little improvising is needed.",
            type: "Counterspell",
            cost: "2 Aether",
            costVal: 2,
            element: .EARTH,
            image: UIImage(named: "HurriedWall"),
            icon: nil,
            cardCode: "EHU",
            Strength: 6,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 34
        PresentedCardModel(
            name: "Wall of Rocks",
            text: "Stonecasters have honed their art for millennia, becoming quite efficient at building formidable defenses.",
            type: "Ward",
            cost: "3 Aether",
            costVal: 3,
            element: .EARTH,
            image: UIImage(named: "WallofRocks"),
            icon: nil,
            cardCode: "EAL",
            Strength: 4,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 35
        PresentedCardModel(
            name: "Water Wonder Wall",
            text: "Watershapers can accomplish feats with a small vial of water that the rest of us would assume impossible.",
            type: "Ward",
            cost: "3 Aether",
            costVal: 3,
            element: .WATER,
            image: UIImage(named: "WaterWonderWall"),
            icon: nil,
            cardCode: "WAT",
            Strength: 3,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 36
        PresentedCardModel(
            name: "Icy Defense",
            text: "This spell blocks 1 less damage from Fire spells.",
            type: "Counterspell",
            cost: "2 Aether",
            costVal: 2,
            element: .WATER,
            image: UIImage(named: "IcyDefense"),
            icon: nil,
            cardCode: "WIC",
            Strength: 5,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 37
        PresentedCardModel(
            name: "Scorching Rebuke",
            text: "At the end of the defend phase, the opponent who attacked you takes aether damage equal to the damage dealt to you this turn.",
            type: "Counterspell",
            cost: "3 Aether",
            costVal: 3,
            element: .FIRE,
            image: UIImage(named: "ScorchingRebuke"),
            icon: nil,
            cardCode: "FSC",
            Strength: 1,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 38
        PresentedCardModel(
            name: "Quick Counterblaze",
            text: "Pyromancers dedicate years of their life to learn how to best grow, control, and direct their blazes. However, that sometimes leaves them out of practice when it comes to dealing with incoming fire.",
            type: "Counterspell",
            cost: "2 Aether",
            costVal: 2,
            element: .FIRE,
            image: UIImage(named: "QuickCounterblaze"),
            icon: nil,
            cardCode: "FQU",
            Strength: 3,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 39
        PresentedCardModel(
            name: "Air-Burst Dodge",
            text: "Airchannelers train to deflect and redirect incoming attacks. In the event that something too heavy comes their way, however, a quick escape may be a better alternative.",
            type: "Counterspell",
            cost: "3 Aether",
            costVal: 3,
            element: .AIR,
            image: UIImage(named: "AirBurstDodge"),
            icon: nil,
            cardCode: "AIR",
            Strength: 6,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 40
        PresentedCardModel(
            name: "Deflecting Gust",
            text: "At the end of the defend phase, the opponent who attacked you takes aether damage equal to the damage blocked by this spell.",
            type: "Counterspell",
            cost: "2 Aether",
            costVal: 2,
            element: .AIR,
            image: UIImage(named: "DeflectingGust"),
            icon: nil,
            cardCode: "ADE",
            Strength: 4,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 41
        PresentedCardModel(
            name: "Mud Vortex",
            text: "Prevent all aether damage you would be dealt by Fire or Water spells.",
            type: "Ward",
            cost: "3 Aether",
            costVal: 3,
            element: .EARTH,
            image: UIImage(named: "MudVortex"),
            icon: nil,
            cardCode: "EMU",
            Strength: 4,
            duration: 2,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 42
        PresentedCardModel(
            name: "Rcks Fall, Everyone Dies",
            text: "Break all items each opponent controls.",
            type: "Jinx",
            cost: "4 Aether",
            costVal: 4,
            element: .EARTH,
            image: UIImage(named: "RocksFallEveryoneDies"),
            icon: nil,
            cardCode: "EEV",
            Strength: 1,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 43
        PresentedCardModel(
            name: "Aquaball",
            text: "Modern practitioners of water magic have adapted the Flaming Monks’ Fireball, with limited success.",
            type: "Jinx",
            cost: "3 Aether",
            costVal: 3,
            element: .WATER,
            image: UIImage(named: "Aquaball"),
            icon: nil,
            cardCode: "WAQ",
            Strength: 6,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 44
        PresentedCardModel(
            name: "Retaliatory Wave",
            text: "Whenever you are dealt damage by an opponent, put that many wave counters on Retaliatory Wave. When this spell fades or breaks, it deals 1 aether damage to each opponent for each wave counter on it.",
            type: "Ward",
            cost: "3 Aether",
            costVal: 3,
            element: .WATER,
            image: UIImage(named: "RetaliatoryWave"),
            icon: nil,
            cardCode: "WET",
            Strength: 2,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 45
        PresentedCardModel(
            name: "Wall of Flames",
            text: "Whenever an opponent attacks you, they take 1 aether damage.",
            type: "Ward",
            cost: "2 Aether",
            costVal: 2,
            element: .FIRE,
            image: UIImage(named: "WallofFlames"),
            icon: nil,
            cardCode: "FWA",
            Strength: 1,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 46
        PresentedCardModel(
            name: "Fireball",
            text: "The Flaming Monks of old have long since faded from existence. This spell remains their greatest achievement, and is one of the only pieces of evidence that they ever existed at all…",
            type: "Jinx",
            cost: "N Aether",
            costVal: 0,
            element: .FIRE,
            image: UIImage(named: "Fireball"),
            icon: nil,
            cardCode: "FIR",
            Strength: 2,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 47
        PresentedCardModel(
            name: "Toxic Fog",
            text: "An opponent dealt aether damage by this spell cannot gain aether until their end of their turn. For that duration, spells they cast cost 1 more aether.",
            type: "Jinx",
            cost: "5 Aether",
            costVal: 5,
            element: .AIR,
            image: UIImage(named: "ToxicFog"),
            icon: nil,
            cardCode: "ANT",
            Strength: 5,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 48
        PresentedCardModel(
            name: "Countervailing Winds",
            text: "Any player attacking you must choose another player to be the target of their attack (they can choose themselves). It becomes that player’s defend phase.",
            type: "Ward",
            cost: "5 Aether",
            costVal: 5,
            element: .AIR,
            image: UIImage(named: "CountervailingWinds"),
            icon: nil,
            cardCode: "AOU",
            Strength: 0,
            duration: 2,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 49
        PresentedCardModel(
            name: "Stone Rain",
            text: "Deal 2 aether damage to each opponent. Each opponent damaged by this spell chooses one item they have. Break it.",
            type: "Jinx",
            cost: "2 Aether",
            costVal: 2,
            element: .EARTH,
            image: UIImage(named: "StoneRain"),
            icon: nil,
            cardCode: "ETO",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 50
        PresentedCardModel(
            name: "Spiked Ground",
            text: "Whenever an opponent casts a non-Ward Spell, that player takes 1 aether damage.",
            type: "Curse",
            cost: "3 Aether",
            costVal: 3,
            element: .EARTH,
            image: UIImage(named: "SpikedGround"),
            icon: nil,
            cardCode: "ESP",
            Strength: 0,
            duration: 4,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 51
        PresentedCardModel(
            name: "Crashing Shores",
            text: "You may skip your attack phase each turn. If you do, put a wave counter on Crashing Shores. When this spell fades or breaks, it deals 2 aether damage to each opponent for each wave counter on it.",
            type: "Curse",
            cost: "3 Aether",
            costVal: 3,
            element: .WATER,
            image: UIImage(named: "CrashingShores"),
            icon: nil,
            cardCode: "WCR",
            Strength: 1,
            duration: 6,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 52
        PresentedCardModel(
            name: "Hydro Vortex",
            text: "The cursed opponent cannot play items for the duration of this spell.",
            type: "Curse",
            cost: "4 Aether",
            costVal: 4,
            element: .WATER,
            image: UIImage(named: "HydroVortex"),
            icon: nil,
            cardCode: "WHY",
            Strength: 1,
            duration: 4,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 53
        PresentedCardModel(
            name: "Flaming Vortex",
            text: "Whenever the cursed opponent plays a defense spell, they take 1 aether damage.",
            type: "Curse",
            cost: "3 Aether",
            costVal: 3,
            element: .FIRE,
            image: UIImage(named: "FlamingVortex"),
            icon: nil,
            cardCode: "FFL",
            Strength: 3,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 54
        PresentedCardModel(
            name: "Scorched Soul",
            text: "When you cast this spell, you may break a charm. If you do, that charm’s controller takes ½*N damage.",
            type: "Curse",
            cost: "N Aether",
            costVal: 0,
            element: .FIRE,
            image: UIImage(named: "ScorchedSoul"),
            icon: nil,
            cardCode: "FCO",
            Strength: nil,
            duration: 2,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 55
        PresentedCardModel(
            name: "Unfriendly Skies",
            text: "Whenever an opponent activates an item, that player may discard a card. If they do not, break a Ward they control and you gain 2 aether.",
            type: "Curse",
            cost: "2 Aether",
            costVal: 2,
            element: .AIR,
            image: UIImage(named: "UnfriendlySkies"),
            icon: nil,
            cardCode: "AUN",
            Strength: 1,
            duration: 2,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 56
        PresentedCardModel(
            name: "Stray Gust",
            text: "Defending opponent pulls a spell or item they have to their hand.",
            type: "Jinx",
            cost: "1 Aether",
            costVal: 1,
            element: .AIR,
            image: UIImage(named: "StrayGust"),
            icon: nil,
            cardCode: "AST",
            Strength: 2,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 57
        PresentedCardModel(
            name: "Earthquake",
            text: "Break all Curses, Wards, and Relics defending opponent controls",
            type: "Jinx",
            cost: "2 Aether",
            costVal: 2,
            element: .EARTH,
            image: UIImage(named: "Earthquake"),
            icon: nil,
            cardCode: "EAR",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 58
        PresentedCardModel(
            name: "Icicle Javelin",
            text: "If defending opponent has a ward, break it. Otherwise, they lose 3 aether.",
            type: "Jinx",
            cost: "3 Aether",
            costVal: 3,
            element: .WATER,
            image: UIImage(named: "IcicleJavelin"),
            icon: nil,
            cardCode: "WCI",
            Strength: 2,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 59
        PresentedCardModel(
            name: "Aetherblaze",
            text: "Each opponent who has a charm loses N aether (round up). They can’t lose more than 6 aether this way.",
            type: "Jinx",
            cost: "N Aether",
            costVal: 0,
            element: .FIRE,
            image: UIImage(named: "Aetherblaze"),
            icon: nil,
            cardCode: "AAE",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 60
        PresentedCardModel(
            name: "Twister’s Gale",
            text: "Choose up to N items. Their player(s) pulls those items to their hand. Each player loses one aether for each item they pulled this way.",
            type: "Jinx",
            cost: "N Aether",
            costVal: 0,
            element: .AIR,
            image: UIImage(named: "TwistersGale"),
            icon: nil,
            cardCode: "ATW",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 61
        PresentedCardModel(
            name: "Hide",
            text: "If you have 3 or less Aether, you take no damage this round.",
            type: "Counterspell",
            cost: "1 Aether",
            costVal: 1,
            element: .EARTH,
            image: UIImage(named: "Hide"),
            icon: nil,
            cardCode: "EHI",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 62
        PresentedCardModel(
            name: "Wall Spikes",
            text: "Passive: Your Earth wards have +2 strength, and when your opponent deals damage to you with a jinx, that player takes 2 aether damage and you destroy this relic.",
            type: "Relic",
            cost: "1 Aether",
            costVal: 1,
            element: .EARTH,
            image: UIImage(named: "WallSpikes"),
            icon: nil,
            cardCode: "ELL",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 63
        PresentedCardModel(
            name: "Waves of Aged Wine",
            text: "Each opponent loses life equal to the number of wave counters on this card.\nPassive: Whenever you put a brew counter on this potion, put a wave counter on it.",
            type: "Potion",
            cost: "N Turns",
            costVal: 0,
            element: .WATER,
            image: UIImage(named: "WavesofAged"),
            icon: nil,
            cardCode: "WAV",
            Strength: nil,
            duration: nil,
            speed: 4,
            hasActivated: false,
            numTargets: nil
        ),
    // 64
        PresentedCardModel(
            name: "Drown",
            text: "This card’s strength is equal to the number of age counters, brew counters, and wave counters among cards you control.",
            type: "Jinx",
            cost: "5 Aether",
            costVal: 5,
            element: .WATER,
            image: UIImage(named: "Drown"),
            icon: nil,
            cardCode: "WDR",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 65
        PresentedCardModel(
            name: "Immolate",
            text: "If you do not win the game during the defend phase this card resolves in, you lose the game.",
            type: "Jinx",
            cost: "8 Aether",
            costVal: 8,
            element: .FIRE,
            image: UIImage(named: "Immolate"),
            icon: nil,
            cardCode: "FIM",
            Strength: 18,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 66
        PresentedCardModel(
            name: "Counterburn",
            text: "If you played a Water counterspell this turn, double this card’s strength",
            type: "Jinx",
            cost: "3 Aether",
            costVal: 3,
            element: .FIRE,
            image: UIImage(named: "Counterburn"),
            icon: nil,
            cardCode: "FOU",
            Strength: 4,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 67
        PresentedCardModel(
            name: "Lightning Vortex",
            text: "Whenever a jinx deals damage to you, the attacking player takes N aether damage, where N is 5 minus the amount of age counters on this ward.",
            type: "Ward",
            cost: "2 Aether",
            costVal: 2,
            element: .AIR,
            image: UIImage(named: "LightningVortex"),
            icon: nil,
            cardCode: "ALI",
            Strength: 2,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        ),
    // 68
        PresentedCardModel(
            name: "Howl",
            text: "The defending player pulls N spells and items to their hand, where N is the amount of aether you have gained the turn this was cast. If they can’t, they pull all their spells and items.",
            type: "Jinx",
            cost: "4 Aether",
            costVal: 4,
            element: .AIR,
            image: UIImage(named: "Howl"),
            icon: nil,
            cardCode: "AHO",
            Strength: 3,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil
        )
    ]
    
    static let cardByCode: [String: PresentedCardModel] = {
        Dictionary(uniqueKeysWithValues: fullCardList.map { ($0.cardCode, $0) })
    }()
}

