//
//  SetCards.swift
//  Spellbook Duels
//
//  Created by Ryan Camp on 10/29/25.
//

import UIKit
import SwiftData

extension PresentedCardModel {
    static let fullCardList: [PresentedCardModel] = [ // Numbered to make it easier to keep track
    // 1
        PresentedCardModel(
            name: "Aspect of Cavern",
            text: "Your earth enchantments and items cannot be broken.",
            type: .charm,
            cost: "2 Aether",
            costVal: 2,
            element: .EARTH,
            image: "AspectofCavern",
            icon: "Aspect of Cavern Icon",
            cardCode: "EAS",
            Strength: nil,
            duration: 5,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 2
        PresentedCardModel(
            name: "Steel Shield",
            text: "Passive: While you have no defense spells, aether damage dealt to you is halved (round down).",
            type: .relic,
            cost: "3 Aether",
            costVal: 3,
            element: .EARTH,
            image: "SteelShield",
            icon: "Steel Shield Icon",
            cardCode: "EST",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 3
        PresentedCardModel(
            name: "Instant Freeze",
            text: "All spells and abilities that have been cast or activated before this potion is activated have no effect. This ability resolves first. Players cannot activate abilities after this potion is activated.",
            type: .potion,
            cost: "4 Turns to brew",
            costVal: 4,
            element: .WATER,
            image: "InstantFreeze",
            icon: "Instant Freeze Icon",
            cardCode: "WIN",
            Strength: nil,
            duration: nil,
            speed: 5,
            hasActivated: true,
            numTargets: nil,
            targetTypes: nil
        ),
    // 4
        PresentedCardModel(
            name: "Aspect of Tide",
            text: "At the end of your action phase, put a wave counter on this spell and on each of your enchantments that have wave counters on them. When this spell fades or breaks, discard your hand and draw a card for each wave counter on it.",
            type: .charm,
            cost: "2 Aether",
            costVal: 2,
            element: .WATER,
            image: "AspectofTide",
            icon: "Aspect of Tide Icon",
            cardCode: "WAS",
            Strength: nil,
            duration: 6,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 5
        PresentedCardModel(
            name: "Aspect of Blaze",
            text: "If you would deal aether damage, you deal twice that damage instead.",
            type: .charm,
            cost: "2 Aether",
            costVal: 2,
            element: .FIRE,
            image: "AspectofBlaze",
            icon: "Aspect of Blaze Icon",
            cardCode: "FAS",
            Strength: nil,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 6
        PresentedCardModel(
            name: "Sparking Projectile",
            text: "Wards cannot reduce the damage your attack spells deal.",
            type: .jinx,
            cost: "2 Aether",
            costVal: 2,
            element: .FIRE,
            image: "SparkingProjectile",
            icon: "Sparking Projectile Icon",
            cardCode: "FSP",
            Strength: 4,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 7
        PresentedCardModel(
            name: "Gale Force Deflection",
            text: "All damage that would be dealt to you this defense phase is dealt to the attacking opponent instead.",
            type: .counterspell,
            cost: "3 Aether",
            costVal: 3,
            element: .AIR,
            image: "GaleForceDeflection",
            icon: "Gale Force Deflection Icon",
            cardCode: "AGA",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 8
        PresentedCardModel(
            name: "Aspect of Breeze",
            text: "If you would gain aether, you gain twice that aether instead (this includes for turn).",
            type: .charm,
            cost: "3 Aether",
            costVal: 3,
            element: .AIR,
            image: "AspectofBreeze",
            icon: "Aspect of Breeze Icon",
            cardCode: "AAS",
            Strength: nil,
            duration: 4,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 9
        PresentedCardModel(
            name: "Wall Reinforcement",
            text: "Wall Reinforcement enters with 6 stone counters on it. Whenever you take aether damage, remove a stone counter from it. Wards you have gain 1 strength for each stone counter on this spell.",
            type: .charm,
            cost: "3 Aether",
            costVal: 3,
            element: .EARTH,
            image: "WallReinforcement",
            icon: "Wall Reinforcement Icon",
            cardCode: "EWA",
            Strength: nil,
            duration: 6,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 10
        PresentedCardModel(
            name: "Bottled Fortitude",
            text: "The next time you would take damage from an Attack spell, prevent that damage.",
            type: .potion,
            cost: "2 Turns to Brew",
            costVal: 2,
            element: .EARTH,
            image: "BottledFortitude",
            icon: "Bottled Fortitude Icon",
            cardCode: "EBO",
            Strength: nil,
            duration: nil,
            speed: 3,
            hasActivated: true,
            numTargets: nil,
            targetTypes: nil
        ),
    // 11
        PresentedCardModel(
            name: "Sleeping Draught",
            text: "The next opponent cannot play spells until the end of their next turn.",
            type: .potion,
            cost: "3 Turns to brew",
            costVal: 3,
            element: .WATER,
            image: "SleepingDraught",
            icon: "Sleeping Draught Icon",
            cardCode: "WSL",
            Strength: nil,
            duration: nil,
            speed: 4,
            hasActivated: true,
            numTargets: nil,
            targetTypes: nil
        ),
    // 12
        PresentedCardModel(
            name: "Building Crescendo",
            text: "Whenever you gain aether, put that many wave counters on Building Crescendo. When this spell fades or breaks, you gain 2 aether for each wave counter on it.",
            type: .charm,
            cost: "2 Aether",
            costVal: 2,
            element: .WATER,
            image: "BuildingCrescendo",
            icon: "Building Crescendo Icon",
            cardCode: "WBU",
            Strength: nil,
            duration: 4,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 13
        PresentedCardModel(
            name: "Stoking the Flames",
            text: "You gain 3 aether each turn instead of 1. If at the end of your turn you have not played a new attack spell, break this charm.",
            type: .charm,
            cost: "1 Aether",
            costVal: 1,
            element: .FIRE,
            image: "StokingtheFlames",
            icon: "Stoking the Flames Icon",
            cardCode: "FST",
            Strength: nil,
            duration: 4,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 14
        PresentedCardModel(
            name: "Purifying Fire",
            text: "Break an opponent’s Curse. Each opponent takes 2 aether damage.",
            type: .potion,
            cost: "2 Turns to Brew",
            costVal: 2,
            element: .FIRE,
            image: "PurifyingFire",
            icon: "Purifying Fire Icon",
            cardCode: "FPU",
            Strength: nil,
            duration: nil,
            speed: 3,
            hasActivated: true,
            numTargets: 1,
            targetTypes: [(.curse, .opponent)]
        ),
    // 15
        PresentedCardModel(
            name: "Flask-Held Gale",
            text: "Break a Ward. Gain aether equal to that card’s cost.",
            type: .potion,
            cost: "2 Turns to Brew",
            costVal: 2,
            element: .AIR,
            image: "FlaskHeldGale",
            icon: "Flask Held Gale Icon",
            cardCode: "AFL",
            Strength: nil,
            duration: nil,
            speed: 3,
            hasActivated: true,
            numTargets: 1,
            targetTypes: [(.ward, nil)]
        ),
    // 16
        PresentedCardModel(
            name: "Meditation",
            text: "Air spells you cast cost 2 less aether to cast.",
            type: .charm,
            cost: "2 Aether",
            costVal: 2,
            element: .AIR,
            image: "Meditation",
            icon: "Meditation Icon",
            cardCode: "AME",
            Strength: nil,
            duration: 2,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 17
        PresentedCardModel(
            name: "Jar of Dirt",
            text: "The next time you would take aether damage, prevent that damage.",
            type: .potion,
            cost: "3 Turns to Brew",
            costVal: 3,
            element: .EARTH,
            image: "JarofDirt",
            icon: "Jar of Dirt Icon",
            cardCode: "EJA",
            Strength: nil,
            duration: nil,
            speed: 5,
            hasActivated: true,
            numTargets: nil,
            targetTypes: nil
        ),
    // 18
        PresentedCardModel(
            name: "Bonecracker",
            text: "An opponent that attacked you this turn takes 3 aether damage.",
            type: .relic,
            cost: "1 Aether",
            costVal: 1,
            element: .EARTH,
            image: "Bonecracker",
            icon: "Bonecracker Icon",
            cardCode: "EON",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 19
        PresentedCardModel(
            name: "Seer’s Scrying Bowl",
            text: "Passive: You may pay 1 aether to look at the top 3 cards of your spellbook any time you have priority.",
            type: .relic,
            cost: "1 Aether",
            costVal: 1,
            element: .WATER,
            image: "SeersScryingBowl",
            icon: "Seer's Scrying Bowl Icon",
            cardCode: "WSE",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: true,
            numTargets: nil,
            targetTypes: nil
        ),
    // 20
        PresentedCardModel(
            name: "Scrying Water",
            text: "Look at the top 4 cards of the Spellbook. Choose one of those cards and put it into your hand, then shuffle the rest back into the Spellbook.",
            type: .potion,
            cost: "1 Turn to Brew",
            costVal: 1,
            element: .WATER,
            image: "ScryingWater",
            icon: "Scrying Water Icon",
            cardCode: "WSC",
            Strength: nil,
            duration: nil,
            speed: 3,
            hasActivated: true,
            numTargets: nil,
            targetTypes: nil
        ),
    // 21
        PresentedCardModel(
            name: "Greek Fire",
            text: "Each opponent takes 4 aether damage for each enchantment and each item they control.",
            type: .potion,
            cost: "4 Turns to Brew",
            costVal: 4,
            element: .FIRE,
            image: "GreekFire",
            icon: "Greek Fire Icon",
            cardCode: "FGR",
            Strength: nil,
            duration: nil,
            speed: 4,
            hasActivated: true,
            numTargets: nil,
            targetTypes: nil
        ),
    // 22
        PresentedCardModel(
            name: "Kindling Staff",
            text: "Deal 3 damage to each opponent without a ward.",
            type: .relic,
            cost: "1 Aether",
            costVal: 1,
            element: .FIRE,
            image: "KindlingStaff",
            icon: "Kindling Staff Icon",
            cardCode: "FKI",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: true,
            numTargets: nil,
            targetTypes: nil
        ),
    // 23
        PresentedCardModel(
            name: "Wax Wings",
            text: "Prevent any damage you would take from non-Fire sources until the end of your next turn.",
            type: .relic,
            cost: "2 Aether",
            costVal: 2,
            element: .AIR,
            image: "WaxWings",
            icon: "Wax Wings Icon",
            cardCode: "AWA",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: true,
            numTargets: nil,
            targetTypes: nil
        ),
    // 24
        PresentedCardModel(
            name: "Breath of Fresh Air",
            text: "You gain 4 aether.",
            type: .potion,
            cost: "3 Turns to Brew",
            costVal: 3,
            element: .AIR,
            image: "BreathofFreshAir",
            icon: "Breath of Fresh Air Icon",
            cardCode: "ABR",
            Strength: nil,
            duration: nil,
            speed: 4,
            hasActivated: true,
            numTargets: nil,
            targetTypes: nil
        ),
    // 25
        PresentedCardModel(
            name: "Earth Wand",
            text: "Passive: Earth wards and counterspells you cast have 3 extra strength.",
            type: .relic,
            cost: "2 Aether",
            costVal: 2,
            element: .EARTH,
            image: "EarthWand",
            icon: "Earth Wand Icon",
            cardCode: "EEA",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 26
        PresentedCardModel(
            name: "Insurmountable",
            text: "Prevent all damage that would be dealt to you this turn.",
            type: .counterspell,
            cost: "5 Aether",
            costVal: 5,
            element: .EARTH,
            image: "Insurmountable",
            icon: "Insurmountable Icon",
            cardCode: "EIN",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 27
        PresentedCardModel(
            name: "Refraction Mirage",
            text: "Flip a coin. If it lands on heads, prevent all damage that would be dealt to you this turn. If tails, prevent half that damage instead, rounded down.",
            type: .counterspell,
            cost: "3 Aether",
            costVal: 3,
            element: .WATER,
            image: "RefractionMirage",
            icon: "Refraction Mirage Icon",
            cardCode: "WRE",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 28
        PresentedCardModel(
            name: "Water Wand",
            text: "Passive: Whenever you cast a Water enchantment, you gain 3 aether.",
            type: .relic,
            cost: "2 Aether",
            costVal: 2,
            element: .WATER,
            image: "WaterWand",
            icon: "Water Wand Icon",
            cardCode: "WWA",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 29
        PresentedCardModel(
            name: "Fire Wand",
            text: "Passive: Whenever you cast a Fire spell, each opponent loses 1 aether.",
            type: .relic,
            cost: "1 Aether",
            costVal: 1,
            element: .FIRE,
            image: "FireWand",
            icon: "Fire Wand Icon",
            cardCode: "FFI",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 30
        PresentedCardModel(
            name: "Blazing Counter",
            text: "The attacking opponent takes 3 aether damage.",
            type: .counterspell,
            cost: "3 Aether",
            costVal: 3,
            element: .FIRE,
            image: "BlazingCounter",
            icon: "Blazing Counter Icon",
            cardCode: "FBL",
            Strength: 4,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 31
        PresentedCardModel(
            name: "Countergale",
            text: "Prevent half the damage you would take this defense phase (round up).",
            type: .counterspell,
            cost: "1 Aether",
            costVal: 1,
            element: .AIR,
            image: "Countergale",
            icon: "Countergale Icon",
            cardCode: "ACO",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 32
        PresentedCardModel(
            name: "Air Wand",
            text: "Passive: Whenever you cast an Air spell, you gain 3 aether.",
            type: .relic,
            cost: "2 Aether",
            costVal: 2,
            element: .AIR,
            image: "AirWand",
            icon: "Air Wand Icon",
            cardCode: "AAI",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 33
        PresentedCardModel(
            name: "Hurried Wall",
            text: "Practicers of the lithomantic arts may not always have time to put up indomitable fortifications. In this case, a little improvising is needed.",
            type: .counterspell,
            cost: "2 Aether",
            costVal: 2,
            element: .EARTH,
            image: "HurriedWall",
            icon: "Hurried Wall Icon",
            cardCode: "EHU",
            Strength: 6,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 34
        PresentedCardModel(
            name: "Wall of Rocks",
            text: "Stonecasters have honed their art for millennia, becoming quite efficient at building formidable defenses.",
            type: .ward,
            cost: "3 Aether",
            costVal: 3,
            element: .EARTH,
            image: "WallofRocks",
            icon: "Wall of Rocks Icon",
            cardCode: "EAL",
            Strength: 4,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 35
        PresentedCardModel(
            name: "Water Wonder Wall",
            text: "Watershapers can accomplish feats with a small vial of water that the rest of us would assume impossible.",
            type: .ward,
            cost: "3 Aether",
            costVal: 3,
            element: .WATER,
            image: "WaterWonderWall",
            icon: "Water Wonder Wall Icon",
            cardCode: "WAT",
            Strength: 3,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 36
        PresentedCardModel(
            name: "Icy Defense",
            text: "This spell blocks 1 less damage from Fire spells.",
            type: .counterspell,
            cost: "2 Aether",
            costVal: 2,
            element: .WATER,
            image: "IcyDefense",
            icon: "Icy Defense Icon",
            cardCode: "WIC",
            Strength: 5,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 37
        PresentedCardModel(
            name: "Scorching Rebuke",
            text: "At the end of the defend phase, the opponent who attacked you takes aether damage equal to the damage dealt to you this turn.",
            type: .counterspell,
            cost: "3 Aether",
            costVal: 3,
            element: .FIRE,
            image: "ScorchingRebuke",
            icon: "Scorching Rebuke Icon",
            cardCode: "FSC",
            Strength: 1,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 38
        PresentedCardModel(
            name: "Quick Counterblaze",
            text: "Pyromancers dedicate years of their life to learn how to best grow, control, and direct their blazes. However, that sometimes leaves them out of practice when it comes to dealing with incoming fire.",
            type: .counterspell,
            cost: "2 Aether",
            costVal: 2,
            element: .FIRE,
            image: "QuickCounterblaze",
            icon: "Quick Counterblaze Icon",
            cardCode: "FQU",
            Strength: 3,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 39
        PresentedCardModel(
            name: "Air-Burst Dodge",
            text: "Airchannelers train to deflect and redirect incoming attacks. In the event that something too heavy comes their way, however, a quick escape may be a better alternative.",
            type: .counterspell,
            cost: "3 Aether",
            costVal: 3,
            element: .AIR,
            image: "AirBurstDodge",
            icon: "Air-Burst Dodge Icon",
            cardCode: "AIR",
            Strength: 6,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 40
        PresentedCardModel(
            name: "Deflecting Gust",
            text: "At the end of the defend phase, the opponent who attacked you takes aether damage equal to the damage blocked by this spell.",
            type: .counterspell,
            cost: "2 Aether",
            costVal: 2,
            element: .AIR,
            image: "DeflectingGust",
            icon: "Deflecting Gust Icon",
            cardCode: "ADE",
            Strength: 4,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 41
        PresentedCardModel(
            name: "Mud Vortex",
            text: "Prevent all aether damage you would be dealt by Fire or Water spells.",
            type: .ward,
            cost: "3 Aether",
            costVal: 3,
            element: .EARTH,
            image: "MudVortex",
            icon: "Mud Vortex Icon",
            cardCode: "EMU",
            Strength: 4,
            duration: 2,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 42
        PresentedCardModel(
            name: "Rocks Fall, Everyone Dies",
            text: "Break all items each opponent controls.",
            type: .jinx,
            cost: "4 Aether",
            costVal: 4,
            element: .EARTH,
            image: "RocksFallEveryoneDies",
            icon: "Rocks Fall, Everyone Dies Icon",
            cardCode: "EEV",
            Strength: 1,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 43
        PresentedCardModel(
            name: "Aquaball",
            text: "Modern practitioners of water magic have adapted the Flaming Monks’ Fireball, with limited success.",
            type: .jinx,
            cost: "3 Aether",
            costVal: 3,
            element: .WATER,
            image: "Aquaball",
            icon: "Aquaball Icon",
            cardCode: "WAQ",
            Strength: 6,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 44
        PresentedCardModel(
            name: "Retaliatory Wave",
            text: "Whenever you are dealt damage by an opponent, put that many wave counters on Retaliatory Wave. When this spell fades or breaks, it deals 1 aether damage to each opponent for each wave counter on it.",
            type: .ward,
            cost: "3 Aether",
            costVal: 3,
            element: .WATER,
            image: "RetaliatoryWave",
            icon: "Retaliatory Wave Icon",
            cardCode: "WET",
            Strength: 2,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 45
        PresentedCardModel(
            name: "Wall of Flames",
            text: "Whenever an opponent attacks you, they take 1 aether damage.",
            type: .ward,
            cost: "2 Aether",
            costVal: 2,
            element: .FIRE,
            image: "WallofFlames",
            icon: "Wall of Flames Icon",
            cardCode: "FWA",
            Strength: 1,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 46
        PresentedCardModel(
            name: "Fireball",
            text: "The Flaming Monks of old have long since faded from existence. This spell remains their greatest achievement, and is one of the only pieces of evidence that they ever existed at all…",
            type: .jinx,
            cost: "N Aether",
            costVal: 0,
            element: .FIRE,
            image: "Fireball",
            icon: "Fireball Icon",
            cardCode: "FIR",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 47
        PresentedCardModel(
            name: "Toxic Fog",
            text: "An opponent dealt aether damage by this spell cannot gain aether until their end of their turn. For that duration, spells they cast cost 1 more aether.",
            type: .jinx,
            cost: "5 Aether",
            costVal: 5,
            element: .AIR,
            image: "ToxicFog",
            icon: "Toxic Fog Icon",
            cardCode: "ANT",
            Strength: 5,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 48
        PresentedCardModel(
            name: "Countervailing Winds",
            text: "All damage that would be dealt to you during your defense phase is dealt to the attacking opponent instead.",
            type: .ward,
            cost: "5 Aether",
            costVal: 5,
            element: .AIR,
            image: "CountervailingWinds",
            icon: "Countervailing Winds Icon",
            cardCode: "AOU",
            Strength: 0,
            duration: 2,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 49
        PresentedCardModel(
            name: "Stone Rain",
            text: "Deal 2 aether damage to each opponent. Each opponent damaged by this spell chooses one item they have. Break it.",
            type: .jinx,
            cost: "2 Aether",
            costVal: 2,
            element: .EARTH,
            image: "StoneRain",
            icon: "Stone Rain Icon",
            cardCode: "ETO",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 50
        PresentedCardModel(
            name: "Spiked Ground",
            text: "Whenever an opponent casts a non-Ward Spell, that player takes 1 aether damage.",
            type: .curse,
            cost: "3 Aether",
            costVal: 3,
            element: .EARTH,
            image: "SpikedGround",
            icon: "Spiked Ground Icon",
            cardCode: "ESP",
            Strength: 0,
            duration: 4,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 51
        PresentedCardModel(
            name: "Crashing Shores",
            text: "You may skip your attack phase each turn. If you do, put a wave counter on Crashing Shores. When this spell fades or breaks, it deals 2 aether damage to each opponent for each wave counter on it.",
            type: .curse,
            cost: "3 Aether",
            costVal: 3,
            element: .WATER,
            image: "CrashingShores",
            icon: "Crashing Shores Icon",
            cardCode: "WCR",
            Strength: 1,
            duration: 6,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 52
        PresentedCardModel(
            name: "Hydro Vortex",
            text: "The cursed opponent cannot play items for the duration of this spell.",
            type: .curse,
            cost: "4 Aether",
            costVal: 4,
            element: .WATER,
            image: "HydroVortex",
            icon: "Hydro Vortex Icon",
            cardCode: "WHY",
            Strength: 1,
            duration: 4,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 53
        PresentedCardModel(
            name: "Flaming Vortex",
            text: "Whenever the cursed opponent plays a defense spell, they take 1 aether damage.",
            type: .curse,
            cost: "3 Aether",
            costVal: 3,
            element: .FIRE,
            image: "FlamingVortex",
            icon: "Flaming Vortex Icon",
            cardCode: "FFL",
            Strength: 3,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 54
        PresentedCardModel(
            name: "Scorched Soul",
            text: "When you cast this spell, you may break a charm. If you do, that charm’s controller takes ½*N damage.",
            type: .curse,
            cost: "N Aether",
            costVal: 0,
            element: .FIRE,
            image: "ScorchedSoul",
            icon: "Scorched Soul Icon",
            cardCode: "FCO",
            Strength: 0,
            duration: 2,
            speed: nil,
            hasActivated: false,
            numTargets: 1,
            targetTypes: [(.charm, nil)]
        ),
    // 55
        PresentedCardModel(
            name: "Unfriendly Skies",
            text: "Whenever an opponent activates an item, that player may discard a card. If they do not, break a Ward they control and you gain 2 aether.",
            type: .curse,
            cost: "2 Aether",
            costVal: 2,
            element: .AIR,
            image: "UnfriendlySkies",
            icon: "Unfriendly Skies Icon",
            cardCode: "AUN",
            Strength: 1,
            duration: 2,
            speed: nil,
            hasActivated: false,
            numTargets: nil, // The ward in question will be handled by a monitor
            targetTypes: nil
        ),
    // 56
        PresentedCardModel(
            name: "Stray Gust",
            text: "Defending opponent pulls a spell or item they have to their hand.",
            type: .jinx,
            cost: "1 Aether",
            costVal: 1,
            element: .AIR,
            image: "StrayGust",
            icon: "Stray Gust Icon",
            cardCode: "AST",
            Strength: 2,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 57
        PresentedCardModel(
            name: "Earthquake",
            text: "Break all Curses, Wards, and Relics defending opponent controls",
            type: .jinx,
            cost: "2 Aether",
            costVal: 2,
            element: .EARTH,
            image: "Earthquake",
            icon: "Earthquake Icon",
            cardCode: "EAR",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 58
        PresentedCardModel(
            name: "Icicle Javelin",
            text: "If defending opponent has a ward, break it. Otherwise, they lose 3 aether.",
            type: .jinx,
            cost: "3 Aether",
            costVal: 3,
            element: .WATER,
            image: "IcicleJavelin",
            icon: "Icicle Javelin Icon",
            cardCode: "WCI",
            Strength: 2,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 59
        PresentedCardModel(
            name: "Aetherblaze",
            text: "Each opponent who has a charm loses N aether (round up). They can’t lose more than 6 aether this way.",
            type: .jinx,
            cost: "N Aether",
            costVal: 0,
            element: .FIRE,
            image: "Aetherblaze",
            icon: "Aetherblaze Icon",
            cardCode: "AAE",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 60
        PresentedCardModel(
            name: "Twister’s Gale",
            text: "Choose up to N items. Their player(s) pulls those items to their hand. Each player loses one aether for each item they pulled this way.",
            type: .jinx,
            cost: "N Aether",
            costVal: 0,
            element: .AIR,
            image: "TwistersGale",
            icon: "Twister’s Gale Icon",
            cardCode: "ATW",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: 0,
            targetTypes: [(.potion, nil), (.relic, nil)] // 2-player client; targets vary with N
        ),
    // 61
        PresentedCardModel(
            name: "Hide",
            text: "If you have 3 or less Aether, you take no damage this round.",
            type: .counterspell,
            cost: "1 Aether",
            costVal: 1,
            element: .EARTH,
            image: "Hide",
            icon: "Hide Icon",
            cardCode: "EHI",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 62
        PresentedCardModel(
            name: "Wall Spikes",
            text: "Passive: Your Earth wards have +2 strength, and when your opponent deals damage to you with a jinx, that player takes 2 aether damage and you destroy this relic.",
            type: .relic,
            cost: "1 Aether",
            costVal: 1,
            element: .EARTH,
            image: "WallSpikes",
            icon: "Wall Spikes Icon",
            cardCode: "ELL",
            Strength: nil,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 63
        PresentedCardModel(
            name: "Waves of Aged Wine",
            text: "Each opponent loses life equal to the number of wave counters on this card.\nPassive: Whenever you put a brew counter on this potion, put a wave counter on it.",
            type: .potion,
            cost: "N Turns",
            costVal: 0,
            element: .WATER,
            image: "WavesofAgedWine",
            icon: "Waves of Aged Wine Icon",
            cardCode: "WAV",
            Strength: nil,
            duration: nil,
            speed: 4,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 64
        PresentedCardModel(
            name: "Drown",
            text: "This card’s strength is equal to the number of age counters, brew counters, and wave counters among cards you control.",
            type: .jinx,
            cost: "5 Aether",
            costVal: 5,
            element: .WATER,
            image: "Drown",
            icon: "Drown Icon",
            cardCode: "WDR",
            Strength: 0,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 65
        PresentedCardModel(
            name: "Immolate",
            text: "If you do not win the game during the defend phase this card resolves in, you lose the game.",
            type: .jinx,
            cost: "8 Aether",
            costVal: 8,
            element: .FIRE,
            image: "Immolate",
            icon: "Immolate Icon",
            cardCode: "FIM",
            Strength: 18,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 66
        PresentedCardModel(
            name: "Counterburn",
            text: "If you played a Water counterspell this turn, double this card’s strength.",
            type: .jinx,
            cost: "3 Aether",
            costVal: 3,
            element: .FIRE,
            image: "Counterburn",
            icon: "Counterburn Icon",
            cardCode: "FOU",
            Strength: 4,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 67
        PresentedCardModel(
            name: "Lightning Vortex",
            text: "Whenever a jinx deals damage to you, the attacking player takes N aether damage, where N is 5 minus the amount of age counters on this ward.",
            type: .ward,
            cost: "2 Aether",
            costVal: 2,
            element: .AIR,
            image: "LightningVortex",
            icon: "Lightning Vortex Icon",
            cardCode: "ALI",
            Strength: 2,
            duration: 3,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil
        ),
    // 68
        PresentedCardModel(
            name: "Howl",
            text: "The defending player pulls N spells and items to their hand, where N is the amount of aether you have gained the turn this was cast. If they can’t, they pull all their spells and items.",
                type: .jinx,
            cost: "4 Aether",
            costVal: 4,
            element: .AIR,
            image: "Howl",
            icon: "Howl Icon",
            cardCode: "AHO",
            Strength: 3,
            duration: nil,
            speed: nil,
            hasActivated: false,
            numTargets: nil,
            targetTypes: nil // Defending player chooses
        )
    ]
    
    static let cardByCode: [String: PresentedCardModel] = {
        Dictionary(uniqueKeysWithValues: fullCardList.map { ($0.cardCode, $0) })
    }()
}

